Refactor borrow book classes
CameronNyb/ITC205_Team16_202060 pull request #8
Opened 2020-08-17 09:05 UTC by CameronNyb

2020-08-17 11:58 UTC, samuli64 commented on src/library/borrowbook/BorrowBookControl.java
> +
D1 brackets

2020-08-17 12:00 UTC, samuli64 commented on src/library/borrowbook/BorrowBookControl.java
> +
D1 Brackets

2020-08-17 12:04 UTC, samuli64 commented on src/library/borrowbook/BorrowBookUI.java
> +                    String memStr = input("Swipe member card (press <enter> to cancel): ");
D3 memStr -> memberIdString

2020-08-17 12:04 UTC, samuli64 commented on src/library/borrowbook/BorrowBookUI.java
> +                        int bId = Integer.valueOf(bookStringInput).intValue();
D4 bId -> bookId

2020-08-17 12:05 UTC, samuli64 commented on src/library/borrowbook/BorrowBookUI.java
> +                    String ans = input("Commit loans? (Y/N): ");
D5 ans -> answer

2020-08-17 12:06 UTC, samuli64 requested changes
Code reviewed, some defects identified. Please address before merge approval.

2020-08-17 13:07 UTC, samuli64 commented on src/library/borrowbook/BorrowBookControl.java
> +    private enum CONTROL_STATE { INITIALISED, READY, RESTRICTED, SCANNING, IDENTIFIED, FINALISING, COMPLETED, CANCELLED };
D6 CONTROL_STATE -> ControlState

2020-08-17 13:08 UTC, samuli64 commented on src/library/borrowbook/BorrowBookUI.java
> +    public static enum UI_STATE { INITIALISED, READY, RESTRICTED, SCANNING, IDENTIFIED, FINALISING, COMPLETED, CANCELLED };
D7 UI_STATE > UIState

2020-08-20 08:48 UTC, CameronNyb commented
Defects 1-7 addressed

2020-08-20 09:05 UTC, samuli64 approved these changes
Reviewed. Defects remediated. Approval to merge.

2020-08-20 09:06 UTC, merged